const FILMS = {
    LOAD: "FILMS_LOAD",
    LOAD_SUCCESS: "FILMS_LOAD_SUCCESS",
    LOAD_FAIL: "FILMS_LOAD_FAIL"
}

const PEOPLE = {
    LOAD: "PEOPLE_LOAD",
    LOAD_SUCCESS: "PEOPLE_LOAD_SUCCESS",
    LOAD_FAIL: "PEOPLE_LOAD_FAIL"
}

export {FILMS, PEOPLE}